apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/rh-hcas-emea/demo-gitops-cicd.git
    targetRevision: HEAD
    path: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s    # the amount to back off
        factor: 2       # factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - SkipDryRunOnMissingResource=true
