apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-gitops
resources:
  - ../../base/namespace
  - argocd.yaml
  - dev
  - stage
  - prod
patches:
  - path: patch-namespace.yaml
    target:
      kind: Namespace
