apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-gitops
resources:
  - ../../base/namespace
  - application.yaml
  - argocd.yaml
  - rolebinding.yaml
  - role.yaml

patches:
  - path: patch-namespace.yaml
    target:
      kind: Namespace
