apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-gitops-argocd-dex-server
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
