apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-gitops-argocd-dex-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-gitops-argocd-dex-server
subjects:
- kind: ServiceAccount
  name: argocd-argocd-dex-server
